### ISSUE TITLE
Problem with log_dirs

### ISSUE THREAD

**Issue by bilby91** [spartansystems/spartan_loggly_rsyslog-cookbook#1]
I can not make log_dirs option work. Is seems that @monitor_files is false always.

Node

```
{
  "default_attributes" : {
    "newrelic" : {
      "server_monitoring" : {
        "hostname" : "app",
        "labels" : "app;"
      }
    },
    "loggly": {
      "log_dirs": [
        {
          "directory": "/var/www/app/shared/log",
          "tag": "heraldo"
        }
      ]
    }
  },
  "run_list": [
    "role[logging]"
   ]
}
```

Logging Role

```
{
  "name" : "Logging",
  "chef_type" : "role",
  "json_class" : "Chef::Role",
  "default_attributes" : {
    "loggly": {
      "token": {
        "from_databag": false,
        "value": "XXXX"
      },
      "tls": {
        "enabled": false
      }
    }
  },
  "run_list" : [
    "recipe[spartan_loggly_rsyslog]"
  ]
}

```

**Comment by squaresurf** [comment]
Hi @bilby91, thank you for opening this issue. There are quite a few things that need to fixed with this cookbook. I'm currently in the process of a massive refactor since forking it. I'm hoping to simplify it greatly. To be honest, I'm tempted to remove the `log_dirs` option all together as it appears to need the files to be in existence for the files in the dir to be watched by rsyslog.

**Comment by bilby91** [comment]
Thanks @squaresurf ! Will try `log_files` then and see what happens. Will keep you posted.

**Comment by bilby91** [comment]
@squaresurf I have the same issue with `log_files`. The proper configurations in the `22-loggly.conf` are not being created. Any idea on what could be happening ?

Thanks!

**Comment by squaresurf** [comment]
Can you post your `22-loggly.conf` and the relevant `log_files` attributes?

**Comment by bilby91** [comment]
Sure.

log_files:

```
{
  "default_attributes" : {
    "loggly": {
      "log_files": [
        {
          "filename": "/var/www/app/shared/log/production.log",
          "tag": "app"
        }
      ]
    }
  },
  "run_list": [
    "recipe[apt]",
    "role[ruby]",
    "role[web]",
    "role[redis]",
    "role[monitor]",
    "role[logging]",
    "recipe[shared::memory]",
    "recipe[postgresql::libpq]"
   ]
}
```

22-loggly.conf

```
# This file was generated by Chef


$template LogglyFormat,"<%pri%>%protocol-version% %timestamp:::date-rfc3339% %HOSTNAME% %app-name% %procid% %msgid% [XXXXXXXX@41058 ] %msg%\n"
```

**Comment by squaresurf** [comment]
There are some other oddities with the generated `22-loggly.conf`. I would expect to also see this line: https://github.com/spartansystems/spartan_loggly_rsyslog-cookbook/blob/master/templates/default/rsyslog-loggly.conf.erb#L38

Do you have any errors? What version of the cookbook are you using?

**Comment by bilby91** [comment]
I don't see any errors :(.

Currently running the last version, `2.1.3`.

**Comment by squaresurf** [comment]
Hmm. I think the best thing is to wait for me to finish my refactor. I'm hoping I will get to it soon. Sorry I couldn't be of more help as I'm still gaining familiarity with this cookbook since forking it. (I've yet to start using it until I finish my refactor)

**Comment by bilby91** [comment]
Thank you very much! Do you have an approximate of when you are going to
finish the refactor ? Just an idea!

Thanks!

Martín

@bilby91

**Comment by squaresurf** [comment]
I'm hoping to gain some progress on this tomorrow. I'll let ya know how it goes.

**Comment by bilby91** [comment]
That would be great!

Thank you very much! Let me know if you need any help!

Martín

@bilby91

**Comment by squaresurf** [comment]
I made great progress on the refactor yesterday. I just need to polish up the tests, then I'll release :smile:. I'm hoping to have this done sometime next week.

**Comment by squaresurf** [comment]
Hi @bilby91, I just released `v3.0.0`. Please let me know what you think! :rocket:

**Comment by bilby91** [comment]
Awesome!!! Next week will be working with the logging stuff again for sure!
Will let you know!

Thanks

Martín.

**Comment by bilby91** [comment]
@squaresurf I'm really sorry I couldn't test this yet. Will try to make some time this week for sure!

Thanks

**Comment by squaresurf** [comment]
No worries. Let me know how it goes.

**Comment by squaresurf** [comment]
@bilby91 I'd love to get this issue closed. Have you had a chance to test this?

**Comment by bilby91** [comment]
@squaresurf I moved to a Docker solution at the end. Either way I will make time to do a quick test.

**Comment by squaresurf** [comment]
Thank you.

**Comment by bilby91** [comment]
@squaresurf I'm cleaning up some issues. I won't be able to verify this. Haven't used chef for A LOT of time after I moved to docker.
